import React, { useState } from 'react';
import { writeFile, saveFileDialog } from '../utils/fileUtils';
import { useNotifications } from '../utils/notifications';

const Extensions: React.FC = () => {
  const [extensionList, setExtensionList] = useState('');
  const [scriptType, setScriptType] = useState<'powershell' | 'bash'>('powershell');
  const [generatedScript, setGeneratedScript] = useState('');
  const { addNotification } = useNotifications();

  const generateScript = () => {
    if (!extensionList.trim()) {
      addNotification({
        type: 'warning',
        message: 'Please enter at least one extension ID',
      });
      return;
    }

    const extensions = extensionList
      .split('\n')
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('#'));

    if (extensions.length === 0) {
      addNotification({
        type: 'warning',
        message: 'No valid extension IDs found',
      });
      return;
    }

    let script = '';

    if (scriptType === 'powershell') {
      script = `# PowerShell script to install VS Code extensions
# Generated by VSCode Super Config Manager

Write-Host "Installing VS Code extensions..." -ForegroundColor Green

`;
      extensions.forEach(ext => {
        script += `code --install-extension ${ext}\n`;
      });
      script += `\nWrite-Host "Installation complete!" -ForegroundColor Green\n`;
    } else {
      script = `#!/bin/bash
# Bash script to install VS Code extensions
# Generated by VSCode Super Config Manager

echo "Installing VS Code extensions..."

`;
      extensions.forEach(ext => {
        script += `code --install-extension ${ext}\n`;
      });
      script += `\necho "Installation complete!"\n`;
    }

    setGeneratedScript(script);
    addNotification({
      type: 'success',
      message: `${scriptType === 'powershell' ? 'PowerShell' : 'Bash'} script generated successfully`,
    });
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(generatedScript);
      addNotification({
        type: 'success',
        message: 'Script copied to clipboard',
      });
    } catch (error) {
      addNotification({
        type: 'error',
        message: 'Failed to copy to clipboard',
      });
    }
  };

  const saveScript = async () => {
    if (!generatedScript) {
      addNotification({
        type: 'warning',
        message: 'Generate a script first',
      });
      return;
    }

    const extension = scriptType === 'powershell' ? 'ps1' : 'sh';
    const defaultName = `install-extensions.${extension}`;
    
    const path = await saveFileDialog(defaultName, [
      { name: scriptType === 'powershell' ? 'PowerShell Script' : 'Shell Script', extensions: [extension] },
    ]);

    if (path) {
      try {
        await writeFile(path, generatedScript);
        addNotification({
          type: 'success',
          message: 'Script saved successfully',
        });
      } catch (error: any) {
        addNotification({
          type: 'error',
          message: `Failed to save script: ${error.message}`,
        });
      }
    }
  };

  const exampleExtensions = `# Common VS Code Extensions (one per line)
ms-python.python
ms-vscode.cpptools
esbenp.prettier-vscode
dbaeumer.vscode-eslint
eamodio.gitlens
ms-vscode-remote.remote-ssh
github.copilot
ms-azuretools.vscode-docker
redhat.vscode-yaml
ms-toolsai.jupyter`;

  const loadExample = () => {
    setExtensionList(exampleExtensions);
  };

  return (
    <div>
      <div className="content-header">
        <h2>Extensions & Scripts</h2>
      </div>
      <div className="content-body">
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Extension List</h3>
          </div>
          
          <div className="form-group">
            <label className="form-label">Extension IDs (one per line)</label>
            <textarea
              className="form-textarea"
              value={extensionList}
              onChange={(e) => setExtensionList(e.target.value)}
              placeholder="publisher.extension-name&#10;e.g., ms-python.python"
              style={{ minHeight: '200px', fontFamily: 'Consolas, Monaco, monospace' }}
            />
            <span className="form-hint">
              Enter extension IDs from the VS Code marketplace (e.g., ms-python.python)
            </span>
          </div>

          <button className="btn btn-secondary" onClick={loadExample}>
            📋 Load Example Extensions
          </button>
        </div>

        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Script Type</h3>
          </div>
          
          <div className="form-group">
            <label className="form-label">Select Script Format</label>
            <div className="flex gap-2">
              <label className="flex" style={{ alignItems: 'center', cursor: 'pointer' }}>
                <input
                  type="radio"
                  name="scriptType"
                  value="powershell"
                  checked={scriptType === 'powershell'}
                  onChange={(e) => setScriptType('powershell')}
                  style={{ marginRight: '8px' }}
                />
                PowerShell (.ps1) - Windows
              </label>
              <label className="flex" style={{ alignItems: 'center', cursor: 'pointer', marginLeft: '20px' }}>
                <input
                  type="radio"
                  name="scriptType"
                  value="bash"
                  checked={scriptType === 'bash'}
                  onChange={(e) => setScriptType('bash')}
                  style={{ marginRight: '8px' }}
                />
                Bash (.sh) - Linux/macOS
              </label>
            </div>
          </div>

          <button className="btn btn-primary" onClick={generateScript}>
            ⚡ Generate Script
          </button>
        </div>

        {generatedScript && (
          <div className="card">
            <div className="card-header">
              <h3 className="card-title">Generated Script</h3>
            </div>
            
            <div className="form-group">
              <textarea
                className="form-textarea"
                value={generatedScript}
                readOnly
                style={{ minHeight: '300px', fontFamily: 'Consolas, Monaco, monospace' }}
              />
            </div>

            <div className="btn-group">
              <button className="btn btn-secondary" onClick={copyToClipboard}>
                📋 Copy to Clipboard
              </button>
              <button className="btn btn-success" onClick={saveScript}>
                💾 Save Script
              </button>
            </div>
          </div>
        )}

        <div className="card">
          <div className="card-header">
            <h3 className="card-title">How to Use</h3>
          </div>
          <ol style={{ paddingLeft: '20px', lineHeight: '1.8' }}>
            <li>List your desired VS Code extensions (one per line)</li>
            <li>Select the script type (PowerShell for Windows or Bash for Linux/macOS)</li>
            <li>Click "Generate Script" to create the installation script</li>
            <li>Copy to clipboard or save to a file</li>
            <li>Run the script to install all extensions at once</li>
          </ol>
          
          <p className="mt-2"><strong>To find extension IDs:</strong></p>
          <ul style={{ paddingLeft: '20px', lineHeight: '1.8' }}>
            <li>Open VS Code Extensions view (Ctrl+Shift+X)</li>
            <li>Click on an extension</li>
            <li>The ID is shown in the format: <code>publisher.extension-name</code></li>
          </ul>

          {scriptType === 'powershell' ? (
            <div className="mt-2">
              <p><strong>Running PowerShell scripts:</strong></p>
              <pre style={{ 
                backgroundColor: 'var(--bg-tertiary)', 
                padding: '12px', 
                borderRadius: '4px',
                fontFamily: 'Consolas, Monaco, monospace',
                fontSize: '13px'
              }}>
                {`# Open PowerShell as Administrator
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
.\\install-extensions.ps1`}
              </pre>
            </div>
          ) : (
            <div className="mt-2">
              <p><strong>Running Bash scripts:</strong></p>
              <pre style={{ 
                backgroundColor: 'var(--bg-tertiary)', 
                padding: '12px', 
                borderRadius: '4px',
                fontFamily: 'Consolas, Monaco, monospace',
                fontSize: '13px'
              }}>
                {`# Make script executable and run
chmod +x install-extensions.sh
./install-extensions.sh`}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Extensions;
